- hosts: all
  name: Autoconverted job legacy-congress-dsvm-api-mysql from old job gate-congress-dsvm-api-mysql-ubuntu-xenial
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          set -e
          set -x
          cat > clonemap.yaml << EOF
          clonemap:
            - name: openstack-infra/devstack-gate
              dest: devstack-gate
          EOF
          /usr/zuul-env/bin/zuul-cloner -m clonemap.yaml --cache-dir /opt/git \
              git://git.openstack.org \
              openstack-infra/devstack-gate
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          cat << 'EOF' >>"/tmp/dg-local.conf"
          [[local|localrc]]
          enable_plugin heat git://git.openstack.org/openstack/heat
          enable_plugin congress git://git.openstack.org/openstack/congress
          enable_plugin murano git://git.openstack.org/openstack/murano
          enable_plugin aodh git://git.openstack.org/openstack/aodh
          enable_plugin mistral git://git.openstack.org/openstack/mistral
          enable_plugin monasca-api git://git.openstack.org/openstack/monasca-api
          enable_plugin neutron https://git.openstack.org/openstack/neutron
          # To deploy congress as multi-process (api, pe, datasources)
          CONGRESS_MULTIPROCESS_DEPLOYMENT=True
          CONGRESS_EXPOSE_ENCRYPTION_KEY_FOR_TEST=True
          LIBS_FROM_GIT=python-congressclient
          ENABLE_CONGRESS_Z3=True
          USE_Z3_RELEASE=4.7.1
          TEMPEST_PLUGINS='/opt/stack/new/congress-tempest-plugin /opt/stack/new/telemetry-tempest-plugin /opt/stack/new/murano-tempest-plugin /opt/stack/new/heat-tempest-plugin /opt/stack/new/mistral-tempest-plugin /opt/stack/new/monasca-tempest-plugin'

          EOF
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          ENABLED_SERVICES=s-proxy,s-object,s-container,s-account,
          ENABLED_SERVICES+=neutron-qos

          export SERVICE_TIMEOUT=120  # default too short for this job
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_REGEX="congress_tempest_plugin"
          export DEVSTACK_GATE_NEUTRON=1
          export PROJECTS="openstack/congress $PROJECTS"
          export PROJECTS="openstack/congress-dashboard $PROJECTS"
          export PROJECTS="openstack/python-congressclient $PROJECTS"
          export PROJECTS="openstack/congress-tempest-plugin $PROJECTS"
          export PROJECTS="openstack/murano $PROJECTS"
          export PROJECTS="openstack/aodh $PROJECTS"
          export PROJECTS="openstack/mistral $PROJECTS"
          export PROJECTS="openstack/python-mistralclient $PROJECTS"
          export PROJECTS="openstack/mistral-tempest-plugin $PROJECTS"
          export PROJECTS="openstack/murano-dashboard $PROJECTS"
          export PROJECTS="openstack/python-muranoclient $PROJECTS"
          export PROJECTS="openstack/python-aodhclient $PROJECTS"
          export PROJECTS="openstack/telemetry-tempest-plugin $PROJECTS"
          export PROJECTS="openstack/murano-tempest-plugin $PROJECTS"
          export PROJECTS="openstack/heat-tempest-plugin $PROJECTS"
          export PROJECTS="openstack/monasca-api $PROJECTS"
          export PROJECTS="openstack/monasca-persister $PROJECTS"
          export PROJECTS="openstack/monasca-common $PROJECTS"
          export PROJECTS="openstack/monasca-agent $PROJECTS"
          export PROJECTS="openstack/monasca-notification $PROJECTS"
          export PROJECTS="openstack/monasca-thresh $PROJECTS"
          export PROJECTS="openstack/monasca-statsd $PROJECTS"
          export PROJECTS="openstack/python-monascaclient $PROJECTS"
          export PROJECTS="openstack/monasca-grafana-datasource $PROJECTS"
          export PROJECTS="openstack/monasca-ui $PROJECTS"
          export PROJECTS="openstack/monasca-tempest-plugin $PROJECTS"

          export ENABLED_SERVICES
          export BRANCH_OVERRIDE=default
          if [ "$BRANCH_OVERRIDE" != "default" ] ; then
              export OVERRIDE_ZUUL_BRANCH=$BRANCH_OVERRIDE
          fi

          if [ "{{ database }}" == "postgresql" ] ; then
              export DEVSTACK_GATE_POSTGRES=1
          fi

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
